CREATE DATABASE MANTENIMIENTO_PRODUCTOS

USE MANTENIMIENTO_PRODUCTOS

CREATE TABLE CATEGORIA
(
ID_CATEGORIA INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
CODIGO AS ('CT' + RIGHT('00' + CONVERT(VARCHAR, ID_CATEGORIA),(2))),
NOMBRE NVARCHAR(30) NOT NULL,
DESCRIPCION NVARCHAR(256) NULL
)

INSERT INTO CATEGORIA VALUES('HERRAMIENTA','LAS MEJORES HERRAMIENTAS')
INSERT INTO CATEGORIA VALUES('PINTURERIA','LAS MEJORES PINTURAS PARA TU CASA')

SELECT * FROM CATEGORIA

GO
-- PROCEDIMIENTO ALMACENADO BUSCAR CATEGORIA
CREATE PROC SP_BUSCARCATEGORIA
@BUSCAR NVARCHAR(20)
AS
	SELECT * FROM CATEGORIA
	WHERE NOMBRE LIKE @BUSCAR + '%'

GO
-- PROCEDIMIENTO ALMACENADO INSERTAR CATEGORIA
CREATE PROC SP_INSERTARCATEGORIA
@NOMBRE NVARCHAR(30),
@DESCRIPCION NVARCHAR(256)
AS
	INSERT INTO CATEGORIA VALUES (@NOMBRE, @DESCRIPCION)

GO
-- PROCEDIMIENTO ALMACENADO EDITAR CATEGORIA
CREATE PROC SP_EDITARCATEGORIA
@IDCATEGORIA INT,
@NOMBRE NVARCHAR(30),
@DESCRIPCION NVARCHAR(256)
AS
	UPDATE CATEGORIA 
	SET NOMBRE = @NOMBRE,
		DESCRIPCION = @DESCRIPCION
	WHERE ID_CATEGORIA = @IDCATEGORIA

GO
-- PROCEDIMIENTO ALMACENADO ELIMINAR CATEGORIA
CREATE PROC SP_ELIMINARCATEGORIA
@IDCATEGORIA INT
AS
	DELETE CATEGORIA 
	WHERE ID_CATEGORIA = @IDCATEGORIA

/* ////////////// END CATEGORIA ////////// */


/* ////////////// MARCA ////////// */

CREATE TABLE MARCA
(
	ID_MARCA INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	CODIGO AS ('MR' + RIGHT('00'+CONVERT(VARCHAR,ID_MARCA),(2))),
	NOMBRE NVARCHAR(30) NOT NULL,
	DESCRIPCION NVARCHAR(256) NULL
)

GO
CREATE PROC SP_BUSCARMARCA
@BUSCAR VARCHAR(30)
AS
	SELECT * FROM MARCA
	WHERE NOMBRE LIKE @BUSCAR + '%'

GO
CREATE PROC SP_INSERTARMARCA
@NOMBRE NVARCHAR(30),
@DESCRIPCION NVARCHAR(256)
AS
	INSERT INTO MARCA VALUES (@NOMBRE, @DESCRIPCION)

GO
CREATE PROC SP_EDITARMARCA
@IDMARCA INT,
@NOMBRE NVARCHAR(30),
@DESCRIPCION NVARCHAR(256)
AS
	UPDATE MARCA
	SET NOMBRE = @NOMBRE,
		DESCRIPCION = @DESCRIPCION
	WHERE ID_MARCA = @IDMARCA

GO
CREATE PROC SP_ELIMINARMARCA
@IDMARCA INT
AS
	DELETE MARCA
	WHERE ID_MARCA = @IDMARCA